const primary = "#FF6B35";
const primaryDark = "#E55A24";
const accent = "#2EC4B6";

export const Colors = {
  light: {
    primary,
    primaryDark,
    accent,
    background: "#F8F9FA",
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    card: "#FFFFFF",
    text: "#1A1A2E",
    textSecondary: "#6B7280",
    textTertiary: "#9CA3AF",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
    tabBar: "#FFFFFF",
    tabBarBorder: "#E5E7EB",
    tint: primary,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: primary,
    inputBackground: "#F3F4F6",
    skeleton: "#E5E7EB",
    overlay: "rgba(0,0,0,0.5)",
    gradient: ["#FF6B35", "#FF8C42"],
    headerBackground: "#FFFFFF",
  },
  dark: {
    primary,
    primaryDark,
    accent,
    background: "#0D0D0D",
    surface: "#1A1A1A",
    surfaceElevated: "#252525",
    card: "#1E1E1E",
    text: "#F9FAFB",
    textSecondary: "#9CA3AF",
    textTertiary: "#6B7280",
    border: "#2D2D2D",
    borderLight: "#1F1F1F",
    success: "#10B981",
    warning: "#F59E0B",
    error: "#EF4444",
    tabBar: "#111111",
    tabBarBorder: "#2D2D2D",
    tint: primary,
    tabIconDefault: "#6B7280",
    tabIconSelected: primary,
    inputBackground: "#252525",
    skeleton: "#2D2D2D",
    overlay: "rgba(0,0,0,0.7)",
    gradient: ["#FF6B35", "#E55A24"],
    headerBackground: "#1A1A1A",
  },
};

export default Colors;
